version: '3.8'

services:
  kernel-fusion-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: kernel-fusion:cpu
    container_name: kernel-fusion-cpu
    volumes:
      - .:/workspace
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "8888:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
    stdin_open: true
    tty: true
    working_dir: /workspace
    command: /bin/bash

  jupyter-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: kernel-fusion:cpu
    container_name: kernel-fusion-jupyter-cpu
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    working_dir: /workspace
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
